export const ROUTES = [
  {
    path: "/",
    type: "home",
    label: "Inicio",
    title: "Random Info",
  },
  {
    path: "/person",
    type: "random",
    label: "Pessoa Fisica",
    title: "Pessoa Fisica",
    apiPath: "/api/ForDevPublic/person/random",
    params: { qt: 1 },
  },
  {
    path: "/company",
    type: "random",
    label: "Empresa (pessoa juridica)",
    title: "Empresa (pessoa juridica)",
    apiPath: "/api/ForDevPublic/company/random",
    params: { qt: 1 },
  },
  {
    path: "/card",
    type: "random",
    label: "Cartao de credito",
    title: "Cartao de credito",
    apiPath: "/api/ForDevPublic/card/random",
    params: { qt: 1 },
  },
  {
    path: "/vehicle",
    type: "random",
    label: "Veiculo",
    title: "Veiculo",
    apiPath: "/api/ForDevPublic/vehicle/random",
    params: { qt: 1 },
  },
  {
    path: "/school",
    type: "random",
    label: "Escola",
    title: "Escola",
    apiPath: "/api/ForDevPublic/escola/random",
    params: { qt: 1 },
  },
  {
    path: "/verify-company",
    type: "verify",
    label: "Verificar empresa",
    title: "Verificar empresa",
  },
  {
    path: "/ibge-nomes",
    type: "data",
    label: "IBGE - Nomes",
    title: "IBGE - Nomes",
  },
  {
    path: "/feriados",
    type: "data",
    label: "Feriados",
    title: "Feriados",
  },
  {
    path: "/bancos",
    type: "data",
    label: "Bancos",
    title: "Bancos",
  },
  {
    path: "/cep",
    type: "data",
    label: "CEP",
    title: "CEP",
  },
  {
    path: "/fipe",
    type: "data",
    label: "FIPE",
    title: "FIPE",
  },
];
